---
- name: Set default {{ role_name }} directory
  set_fact:
    gitlab_directory: /srv/{{ role_name }}

- name: Ensure {{ role_name }} directory exists
  file:
    path: "{{ gitlab_directory }}"
    state: directory
    mode: '0755'

- name: Pull and run {{ role_name }} container
  community.docker.docker_container:
    name: "{{ role_name }}"
    image: "{{ docker_images.get(role_name) }}"    
    restart_policy: always
    ports:
      - '8008:80'
      - '8090:8090'
      - '4443:443'
      - '2222:22'
      - '5005:5005'
    env:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://{{ansible_host}}:8090'  
        nginx['listen_port'] = 8090
    volumes:
      - '{{ gitlab_directory }}/config:/etc/gitlab'
      - '{{ gitlab_directory }}/logs:/var/log/gitlab'
      - '{{ gitlab_directory }}/data:/var/opt/gitlab'
    shm_size: '2g'